name: super_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.1
  flame_audio: ^2.10.1
  audioplayers: ^5.2.1
  image_picker: ^1.0.4
  share_plus: ^7.2.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  webdev: ^3.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/cat-acrobat-icon.png
    - assets/audio/cat-meow.mp3
    - assets/images/wolf_of_wall_street.png
    - assets/images/piglet.png
    - assets/images/background.png



